=== calculatelinux/gentoo/metadata/dtd/metadata.dtd
<!-- Metadata for a category -->
<!ELEMENT catmetadata ( (longdescription)* )>

<!-- Metadata for a package -->
<!ELEMENT pkgmetadata ( (maintainer|longdescription|slots|stabilize-allarches|straight-to-stable|use|upstream)* )>

  <!-- One tag for each maintainer of a package, multiple allowed-->
  <!ELEMENT maintainer (email|name|description)+>
  <!-- type attribute determines whether the maintainer is a person or a project.
    Unknown is added to handle <maintainer/>s in <upstream/>s. Using it (or no
    explicit type) for Gentoo maintainers is prohibited. -->
  <!ATTLIST maintainer type (person|project|unknown) "unknown">
  <!-- proxied attribute determines whether the maintainer is a proxied
    maintainer (yes), regular dev (no) or a proxy for somebody (proxy). It is
    valid only for Gentoo maintainers. -->
  <!ATTLIST maintainer proxied (yes|no|proxy) "no">

  <!-- A long description of the package in freetext-->
  <!ELEMENT longdescription (#PCDATA|pkg|cat)* >

  <!-- A description of the packages SLOTs -->
  <!ELEMENT slots ((slot)*,subslots?) >
    <!-- A particular SLOT -->
    <!ELEMENT slot (#PCDATA)* >
      <!-- name attribute holds the name of the SLOT, for sub-SLOTS
      use the subslots element. A slot name of '*' can be used to
      indicate a single description applying to all the slots in which
      case no other <slot/> elements may be present. -->
      <!ATTLIST slot name CDATA #REQUIRED >
    <!-- The meaning of sub-SLOTs for the whole package -->
    <!ELEMENT subslots (#PCDATA)* >

  <!-- whether it's possible to stabilize ALLARCHES -->
  <!ELEMENT stabilize-allarches EMPTY>

  <!-- whether stable keywords should be retained on version bumps -->
  <!ELEMENT straight-to-stable EMPTY>

  <!-- description of what this USE flag does for this package -->
  <!ELEMENT use (flag)* >
    <!ELEMENT flag (#PCDATA|pkg|cat)* >
      <!-- name attribute holds the name of the USE flag -->
      <!ATTLIST flag name CDATA #REQUIRED >

  <!-- upstream metadata information (maintainers, upstream docs,..) -->
  <!ELEMENT upstream (maintainer|changelog|doc|bugs-to|remote-id)* >
    <!-- Due to the limitation of DTD this will also allow a status
      attribute for the package maintainer element. Please note that
      the usage of the status attribute is nevertheless _only_ allowed
      in the upstream maintainer element. -->
    <!ATTLIST maintainer status (active|inactive|unknown) "unknown" >
    <!-- URL where the upstream changelog can be found -->
    <!ELEMENT changelog (#PCDATA)>
    <!-- URL where the location of the upstream documentation can be found -->
    <!ELEMENT doc (#PCDATA)>
      <!ATTLIST doc lang CDATA "en" >
    <!-- location where to report bugs
      (may also be an email address prefixed with mailto:) -->
    <!ELEMENT bugs-to (#PCDATA)>
    <!-- specify a type of package identification tracker -->
    <!ELEMENT remote-id (#PCDATA)>
      <!ATTLIST remote-id type (bitbucket|codeberg|cpan|cpan-module|cpe|cran|ctan|freedesktop-gitlab|gentoo|github|gitlab|gnome-gitlab|google-code|hackage|heptapod|kde-invent|launchpad|osdn|pear|pecl|pypi|rubygems|savannah|savannah-nongnu|sourceforge|sourcehut|vim) #REQUIRED>

  <!-- category/package information for cross-linking in descriptions
    and useflag descriptions -->
  <!ELEMENT pkg (#PCDATA) >
  <!ELEMENT cat (#PCDATA) >

<!-- Common attributes -->

<!-- the lang attribute, specifies the language of this tag in the
  form of an IETF (BCP 47) language tag. This is only useful for
  descriptions of various kinds. If a tag with this attribute is
  included there must be a description in the default language "en" -->
  <!ATTLIST description lang CDATA "en" >
  <!ATTLIST longdescription lang CDATA "en" >
  <!ATTLIST slots lang CDATA "en" >
  <!ATTLIST use lang CDATA "en" >

<!-- The restrict attribute, this attribute specifies restrictions on
  the applicability of tags on versions. The format of this attribute is
  equal to the format of DEPEND lines in ebuilds. Only package
  dependency specifications conforming to EAPI=0 syntax are allowed.
  The dependency specification may only contain references to the
  package itself and no other package.

  For required tags, there must be either an unrestricted version, or a
  version that is default restricted. -->
  <!ATTLIST maintainer restrict CDATA #IMPLIED >
  <!ATTLIST longdescription restrict CDATA #IMPLIED >
  <!ATTLIST flag restrict CDATA #IMPLIED >
  <!ATTLIST stabilize-allarches restrict CDATA #IMPLIED >
  <!ATTLIST straight-to-stable restrict CDATA #IMPLIED >

<!-- standard parts -->
<!-- an email address -->
<!ELEMENT email (#PCDATA) >
<!-- the name of a person (maintainer, contributor) -->
<!ELEMENT name (#PCDATA) >
<!-- A description of a maintainer or change -->
<!ELEMENT description (#PCDATA) >

=== calculatelinux/gentoo/kde-plasma/kwin-x11/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="project">
		<email>kde@gentoo.org</email>
		<name>Gentoo KDE Project</name>
	</maintainer>
	<upstream>
		<bugs-to>https://bugs.kde.org/enter_bug.cgi?product=kwin</bugs-to>
		<remote-id type="kde-invent">plasma/kwin-x11</remote-id>
	</upstream>
	<use>
		<flag name="lock">Enable screen locking via <pkg>kde-plasma/kscreenlocker</pkg></flag>
		<flag name="nightlight">Enable night light support via <pkg>kde-plasma/knighttime</pkg></flag>
		<flag name="shortcuts">Enable global shortcuts support via <pkg>kde-plasma/kglobalacceld</pkg></flag>
	</use>
</pkgmetadata>

=== calculatelinux/gentoo/app-emacs/elfeed/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">

<pkgmetadata>
  <maintainer type="project">
    <email>gnu-emacs@gentoo.org</email>
    <name>Gentoo GNU Emacs project</name>
  </maintainer>
  <maintainer type="person">
    <email>sam@gentoo.org</email>
    <name>Sam James</name>
  </maintainer>
  <longdescription>
    Elfeed is an extensible web feed reader for Emacs, supporting both Atom and
    RSS. Elfeed was inspired by notmuch.
  </longdescription>
  <upstream>
    <bugs-to>https://github.com/emacs-elfeed/elfeed/issues/</bugs-to>
    <remote-id type="github">emacs-elfeed/elfeed</remote-id>
  </upstream>
</pkgmetadata>

=== calculatelinux/gentoo/kde-apps/kdepim-runtime/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="project">
		<email>kde@gentoo.org</email>
		<name>Gentoo KDE Project</name>
	</maintainer>
	<upstream>
		<bugs-to>https://bugs.kde.org/enter_bug.cgi?product=kdepim</bugs-to>
		<remote-id type="kde-invent">pim/kdepim-runtime</remote-id>
	</upstream>
	<use>
		<flag name="activities">Enable Plasma Activities support via kde-plasma/plasma-activities</flag>
		<flag name="ews">Enable support for Microsoft Exchange Web Services</flag>
	</use>
</pkgmetadata>

=== calculatelinux/gentoo/dev-cpp/jwt-cpp/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer type="person" proxied="yes">
    <email>o.freyermuth@googlemail.com</email>
    <name>Oliver Freyermuth</name>
  </maintainer>
  <maintainer type="person">
    <email>amadio@gentoo.org</email>
    <name>Guilherme Amadio</name>
  </maintainer>
  <maintainer type="project" proxied="proxy">
    <email>proxy-maint@gentoo.org</email>
    <name>Proxy Maintainers</name>
  </maintainer>
  <upstream>
    <bugs-to>https://github.com/Thalhammer/jwt-cpp/issues</bugs-to>
    <remote-id type="github">Thalhammer/jwt-cpp</remote-id>
  </upstream>
  <use>
    <flag name="jsoncons">Enable use of <pkg>dev-cpp/jsoncons</pkg></flag>
    <flag name="picojson">Enable use of <pkg>dev-cpp/picojson</pkg></flag>
  </use>
</pkgmetadata>

=== calculatelinux/gentoo/kde-plasma/kdeplasma-addons/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="project">
		<email>kde@gentoo.org</email>
		<name>Gentoo KDE Project</name>
	</maintainer>
	<upstream>
		<bugs-to>https://bugs.kde.org/enter_bug.cgi?product=plasmashell</bugs-to>
		<remote-id type="kde-invent">plasma/kdeplasma-addons</remote-id>
	</upstream>
	<use>
		<flag name="alternate-calendar">Support alternate calendar systems (currently Chinese or Indian) via <pkg>dev-libs/icu</pkg></flag>
		<flag name="led">Synchronizes device LEDs with the Plasma accent color (ultimately requires rust)</flag>
		<flag name="share">Enable applet for quickly sharing data to a variety of sources</flag>
		<flag name="webengine">Enable dictionary and web browser applets using <pkg>dev-qt/qtwebengine</pkg></flag>
	</use>
</pkgmetadata>

=== calculatelinux/gentoo/dev-python/pytest-codeblocks/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="project">
		<email>python@gentoo.org</email>
		<name>Python</name>
	</maintainer>
	<upstream>
		<remote-id type="github">nschloe/pytest-codeblocks</remote-id>
		<remote-id type="pypi">pytest-codeblocks</remote-id>
	</upstream>
	<stabilize-allarches/>
</pkgmetadata>

=== calculatelinux/gentoo/dev-db/valkey/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>sam@gentoo.org</email>
		<name>Sam James</name>
	</maintainer>
	<use>
		<flag name="tcmalloc">
			Use tcmalloc from <pkg>dev-util/google-perftools</pkg> for allocations.
		</flag>
	</use>
	<upstream>
		<remote-id type="github">valkey-io/valkey</remote-id>
	</upstream>
</pkgmetadata>

=== calculatelinux/gentoo/sci-ml/caffe2/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>tupone@gentoo.org</email>
		<name>Tupone Alfredo</name>
	</maintainer>
	<use>
		<flag name="cusparselt">Use the CUDA/HIP Sparse Matrix Multiplication</flag>
		<flag name="distributed">Support distributed applications</flag>
		<flag name="fbgemm">Use <pkg>sci-ml/FBGEMM</pkg></flag>
		<flag name="flash">Enable flash attention</flag>
		<flag name="gloo">Use <pkg>sci-ml/gloo</pkg></flag>
		<flag name="kineto">Use<pkg>sci-ml/kineto</pkg>profiling library</flag>
		<flag name="memefficient">Enable mem efficient attention</flag>
		<flag name="mimalloc">Use <pkg>dev-libs/mimalloc</pkg> as replacement for system malloc</flag>
		<flag name="mkl">Use <pkg>sci-libs/mkl</pkg> for blas, lapack and sparse blas routines</flag>
		<flag name="nccl">Use <pkg>dev-libs/rccl</pkg> (NCCL compatible) backend for distributed operations</flag>
		<flag name="nnpack">Use <pkg>sci-ml/NNPACK</pkg></flag>
		<flag name="numpy">Add support for math operations through numpy</flag>
		<flag name="onednn">Use <pkg>sci-ml/oneDNN</pkg></flag>
		<flag name="openblas">Use <pkg>sci-libs/openblas</pkg> for blas routines</flag>
		<flag name="qnnpack">Use QNNPACK</flag>
		<flag name="rocm">Enable ROCm gpu computing support</flag>
		<flag name="xnnpack">Use <pkg>sci-ml/XNNPACK</pkg></flag>
	</use>
	<upstream>
		<remote-id type="github">pytorch/pytorch</remote-id>
	</upstream>
</pkgmetadata>
