=== calculatelinux/gentoo/metadata/dtd/metadata.dtd
<!-- Metadata for a category -->
<!ELEMENT catmetadata ( (longdescription)* )>

<!-- Metadata for a package -->
<!ELEMENT pkgmetadata ( (maintainer|longdescription|slots|stabilize-allarches|straight-to-stable|use|upstream)* )>

  <!-- One tag for each maintainer of a package, multiple allowed-->
  <!ELEMENT maintainer (email|name|description)+>
  <!-- type attribute determines whether the maintainer is a person or a project.
    Unknown is added to handle <maintainer/>s in <upstream/>s. Using it (or no
    explicit type) for Gentoo maintainers is prohibited. -->
  <!ATTLIST maintainer type (person|project|unknown) "unknown">
  <!-- proxied attribute determines whether the maintainer is a proxied
    maintainer (yes), regular dev (no) or a proxy for somebody (proxy). It is
    valid only for Gentoo maintainers. -->
  <!ATTLIST maintainer proxied (yes|no|proxy) "no">

  <!-- A long description of the package in freetext-->
  <!ELEMENT longdescription (#PCDATA|pkg|cat)* >

  <!-- A description of the packages SLOTs -->
  <!ELEMENT slots ((slot)*,subslots?) >
    <!-- A particular SLOT -->
    <!ELEMENT slot (#PCDATA)* >
      <!-- name attribute holds the name of the SLOT, for sub-SLOTS
      use the subslots element. A slot name of '*' can be used to
      indicate a single description applying to all the slots in which
      case no other <slot/> elements may be present. -->
      <!ATTLIST slot name CDATA #REQUIRED >
    <!-- The meaning of sub-SLOTs for the whole package -->
    <!ELEMENT subslots (#PCDATA)* >

  <!-- whether it's possible to stabilize ALLARCHES -->
  <!ELEMENT stabilize-allarches EMPTY>

  <!-- whether stable keywords should be retained on version bumps -->
  <!ELEMENT straight-to-stable EMPTY>

  <!-- description of what this USE flag does for this package -->
  <!ELEMENT use (flag)* >
    <!ELEMENT flag (#PCDATA|pkg|cat)* >
      <!-- name attribute holds the name of the USE flag -->
      <!ATTLIST flag name CDATA #REQUIRED >

  <!-- upstream metadata information (maintainers, upstream docs,..) -->
  <!ELEMENT upstream (maintainer|changelog|doc|bugs-to|remote-id)* >
    <!-- Due to the limitation of DTD this will also allow a status
      attribute for the package maintainer element. Please note that
      the usage of the status attribute is nevertheless _only_ allowed
      in the upstream maintainer element. -->
    <!ATTLIST maintainer status (active|inactive|unknown) "unknown" >
    <!-- URL where the upstream changelog can be found -->
    <!ELEMENT changelog (#PCDATA)>
    <!-- URL where the location of the upstream documentation can be found -->
    <!ELEMENT doc (#PCDATA)>
      <!ATTLIST doc lang CDATA "en" >
    <!-- location where to report bugs
      (may also be an email address prefixed with mailto:) -->
    <!ELEMENT bugs-to (#PCDATA)>
    <!-- specify a type of package identification tracker -->
    <!ELEMENT remote-id (#PCDATA)>
      <!ATTLIST remote-id type (bitbucket|codeberg|cpan|cpan-module|cpe|cran|ctan|freedesktop-gitlab|gentoo|github|gitlab|gnome-gitlab|google-code|hackage|heptapod|kde-invent|launchpad|osdn|pear|pecl|pypi|rubygems|savannah|savannah-nongnu|sourceforge|sourcehut|vim) #REQUIRED>

  <!-- category/package information for cross-linking in descriptions
    and useflag descriptions -->
  <!ELEMENT pkg (#PCDATA) >
  <!ELEMENT cat (#PCDATA) >

<!-- Common attributes -->

<!-- the lang attribute, specifies the language of this tag in the
  form of an IETF (BCP 47) language tag. This is only useful for
  descriptions of various kinds. If a tag with this attribute is
  included there must be a description in the default language "en" -->
  <!ATTLIST description lang CDATA "en" >
  <!ATTLIST longdescription lang CDATA "en" >
  <!ATTLIST slots lang CDATA "en" >
  <!ATTLIST use lang CDATA "en" >

<!-- The restrict attribute, this attribute specifies restrictions on
  the applicability of tags on versions. The format of this attribute is
  equal to the format of DEPEND lines in ebuilds. Only package
  dependency specifications conforming to EAPI=0 syntax are allowed.
  The dependency specification may only contain references to the
  package itself and no other package.

  For required tags, there must be either an unrestricted version, or a
  version that is default restricted. -->
  <!ATTLIST maintainer restrict CDATA #IMPLIED >
  <!ATTLIST longdescription restrict CDATA #IMPLIED >
  <!ATTLIST flag restrict CDATA #IMPLIED >
  <!ATTLIST stabilize-allarches restrict CDATA #IMPLIED >
  <!ATTLIST straight-to-stable restrict CDATA #IMPLIED >

<!-- standard parts -->
<!-- an email address -->
<!ELEMENT email (#PCDATA) >
<!-- the name of a person (maintainer, contributor) -->
<!ELEMENT name (#PCDATA) >
<!-- A description of a maintainer or change -->
<!ELEMENT description (#PCDATA) >

=== calculatelinux/gentoo/dev-vcs/darcs/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="project">
		<email>haskell@gentoo.org</email>
		<name>Gentoo Haskell</name>
	</maintainer>
	<use>
		<flag name="curl">Use libcurl for HTTP support.</flag>
		<flag name="terminfo">Use the terminfo package for enhanced console support.</flag>
	</use>
	<upstream>
		<remote-id type="hackage">darcs</remote-id>
	</upstream>
</pkgmetadata>

=== calculatelinux/gentoo/sys-power/nct6687d/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>nowa@gentoo.org</email>
		<name>Nowa Ammerlaan</name>
	</maintainer>
	<longdescription>
		This kernel module enables recognition of the Nuvoton NCT6687-R chipset in <pkg>sys-apps/lm-sensors</pkg>.
		This sensor is present on some motherboards from, for example, MSI or ASUS.
	</longdescription>
	<upstream>
		<remote-id type="github">Fred78290/nct6687d</remote-id>
		<bugs-to>https://github.com/Fred78290/nct6687d/issues</bugs-to>
	</upstream>
</pkgmetadata>

=== calculatelinux/gentoo/www-servers/caddy/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer type="person">
    <email>zmedico@gentoo.org</email>
    <name>Zac Medico</name>
  </maintainer>
  <maintainer type="person" proxied="yes">
    <email>me@rahil.rocks</email>
    <name>Rahil Bhimjiani</name>
  </maintainer>
  <maintainer type="project" proxied="proxy">
    <email>proxy-maint@gentoo.org</email>
    <name>Proxy Maintainers</name>
  </maintainer>
  <use>
    <flag name="dynamicdns">
      Adds module which allows querying an endpoint to get dynamic public IP and updating records with DNS providers
      https://caddyserver.com/docs/modules/dynamic_dns
    </flag>
    <flag name="dns-alidns">
      Adds module which allows to manage Aliyun DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.alidns
    </flag>
    <flag name="dns-azure">
      Adds module which allows to manage Azure hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.azure
    </flag>
    <flag name="dns-cloudflare">
      Adds module which allows to manage Cloudflare hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.cloudflare
    </flag>
    <flag name="dns-cloudns">
      Adds module which allows to manage ClouDNS hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.cloudns
    </flag>
    <flag name="dns-digitalocean">
      Adds module which allows to manage DigitalOcean hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.digitalocean
    </flag>
    <flag name="dns-duckdns">
      Adds module which allows to manage Duck DNS hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.duckdns
    </flag>
    <flag name="dns-dynv6">
      Adds module which allows to manage Dynv6 hosted DNS zones using Caddy
    </flag>
    <flag name="dns-gandi">
      Adds module which allows to manage Gandi hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.gandi
    </flag>
    <flag name="dns-godaddy">
      Adds module which allows to manage Godaddy hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.godaddy
    </flag>
    <flag name="dns-googleclouddns">
      Adds module which allows to manage Google Cloud hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.googleclouddns
    </flag>
    <flag name="dns-he">
      Adds module which allows to manage Hurricane Electric hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.he
    </flag>
    <flag name="dns-hetzner">
      Adds module which allows to manage Hetzner hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.hetzner
    </flag>
    <flag name="dns-huaweicloud">
      Adds module which allows to manage Huawei Cloud hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.huaweicloud
    </flag>
    <flag name="dns-linode">
      Adds module which allows to manage Linode hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.linode
    </flag>
    <flag name="dns-mailinabox">
      Adds module which allows to manage Mail-in-a-Box hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.mailinabox
    </flag>
    <flag name="dns-namecheap">
      Adds module which allows to manage Namecheap hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.namecheap
    </flag>
    <flag name="dns-netcup">
      Adds module which allows to manage netcup hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.netcup
    </flag>
    <flag name="dns-netlify">
      Adds module which allows to manage Netlify hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.netlify
    </flag>
    <flag name="dns-oraclecloud">
      Adds module which allows to manage Oracle cloud hosted DNS zones using Caddy
      https://github.com/caddy-dns/oraclecloud
    </flag>
    <flag name="dns-ovh">
      Adds module which allows to manage OVHcloud hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.ovh
    </flag>
    <flag name="dns-porkbun">
      Adds module which allows to manage porkbun hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.porkbun
    </flag>
    <flag name="dns-powerdns">
      Adds module which allows to manage DNS zones of <pkg>net-dns/pdns</pkg> using Caddy
      https://caddyserver.com/docs/modules/dns.providers.powerdns
    </flag>
    <flag name="dns-rfc2136">
      Adds module which allows to manage DNS zones using RFC2136 Dynamic Updates within Caddy
      https://caddyserver.com/docs/modules/dns.providers.rfc2136
    </flag>
    <flag name="dns-route53">
      Adds module which allows to manage AWS route53 hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.route53
    </flag>
    <flag name="dns-unifi">
      Adds module which allows to manage UniFi networks DNS zones using Caddy
      https://github.com/caddy-dns/unifi
    </flag>
    <flag name="dns-vultr">
      Adds module which allows to manage Vultr hosted DNS zones using Caddy
      https://caddyserver.com/docs/modules/dns.providers.vultr
    </flag>
    <flag name="events-handlers-exec">
      Adds module which lets user exec command on Caddy events
      https://caddyserver.com/docs/modules/events.handlers.exec
      https://caddyserver.com/docs/caddyfile/options#event-options
    </flag>
    <flag name="security">
      Authentication, Authorization, and Accounting. LDAP, OAuth, SAML, MFA, 2FA, JWT etc..
      https://caddyserver.com/docs/modules/security
    </flag>
    <flag name="webdav">
      Adds module which implements an HTTP handler for responding to WebDAV clients
      https://caddyserver.com/docs/modules/http.handlers.webdav
    </flag>
  </use>
  <upstream>
    <remote-id type="github">caddyserver/caddy</remote-id>
    <bugs-to>https://github.com/caddyserver/caddy/issues</bugs-to>
    <doc>https://caddyserver.com/docs/</doc>
  </upstream>
</pkgmetadata>

=== calculatelinux/gentoo/dev-go/delve/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
    <maintainer type="person">
        <email>oz.tiram@gmail.com</email>
        <name>Oz Tiram</name>
    </maintainer>
    <maintainer type="project">
        <email>proxy-maint@gentoo.org</email>
        <name>Proxy Maintainers</name>
    </maintainer>
	<maintainer type="person">
		<email>arthurzam@gentoo.org</email>
		<name>Arthur Zamarin</name>
	</maintainer>
    <upstream>
        <remote-id type="github">go-delve/delve</remote-id>
    </upstream>
</pkgmetadata>

=== calculatelinux/gentoo/media-video/ffmpeg-compat/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>ionen@gentoo.org</email>
		<name>Ionen Wolkens</name>
	</maintainer>
	<maintainer type="person">
		<email>chewi@gentoo.org</email>
		<name>James Le Cuirot</name>
		<description>soc USE flag</description>
	</maintainer>
	<use>
		<flag name="amf">Enable AMD's Advanced Media Framework support via <pkg>media-video/amdgpu-pro-amf</pkg></flag>
		<flag name="amr">Enable Adaptive Multi-Rate Audio support via <pkg>media-libs/opencore-amr</pkg></flag>
		<flag name="amrenc">Enable Adaptive Multi-Rate Audio encoding support via <pkg>media-libs/vo-amrwbenc</pkg></flag>
		<flag name="appkit">Enable Apple AppKit framework</flag>
		<flag name="bluray">Enable Blu-ray filesystems reading support via <pkg>media-libs/libbluray</pkg></flag>
		<flag name="bs2b">Enable Bauer Stereo-to-Binaural filter support via <pkg>media-libs/libbs2b</pkg></flag>
		<flag name="cdio">Enable audio CDs reading via <pkg>dev-libs/libcdio-paranoia</pkg></flag>
		<flag name="chromaprint">Enable audio fingerprinting support via <pkg>media-libs/chromaprint</pkg></flag>
		<flag name="codec2">Enable codec2 low bit rate speech codec support via <pkg>media-libs/codec2</pkg></flag>
		<flag name="cuda-clang">Enable support for various GPU-accelerated filters using NVIDIA PTX compiled with <pkg>llvm-core/clang</pkg></flag>
		<flag name="dav1d">Enable AV1 decoding support via <pkg>media-libs/dav1d</pkg></flag>
		<flag name="drm">
			Enable use of <pkg>x11-libs/libdrm</pkg> for various hardware
			accelerated functions and Kernel Mode Setting screen capture
		</flag>
		<flag name="fdk">
			Enable AAC (Advanced Audio Coding) encoding support via
			<pkg>media-libs/fdk-aac</pkg> in addition to FFmpeg's own
			implementation (warning: if USE=gpl is enabled, this produces
			a non-redistributable build)
		</flag>
		<flag name="flite">Enable text-to-speech filter support via <pkg>app-accessibility/flite</pkg></flag>
		<flag name="frei0r">Enable use of filters through <pkg>media-plugins/frei0r-plugins</pkg></flag>
		<flag name="fribidi">Enable Bidi support for the drawtext filter via <pkg>dev-libs/fribidi</pkg></flag>
		<flag name="gcrypt">
			Enable using <pkg>dev-libs/libgcrypt</pkg> for rtmp(t)e support (not
			needed if using any of USE=gmp,librtmp,openssl), and for obtaining
			random bytes (not needed if USE=openssl)</flag>
		<flag name="gme">Enables various game music formats support via <pkg>media-libs/game-music-emu</pkg></flag>
		<flag name="gnutls">
			Enable using <pkg>net-libs/gnutls</pkg> for TLS/HTTPS support
			and other minor functions (has no effect if USE=openssl is set)
		</flag>
		<flag name="gpl">Enable use of GPL licensed code, should be kept enabled unless LGPL binaries are needed</flag>
		<flag name="iec61883">Enable FireWire DV/HDV input device support via <pkg>media-libs/libiec61883</pkg></flag>
		<flag name="kvazaar">Enable H.265/HEVC encoding support via <pkg>media-libs/kvazaar</pkg></flag>
		<flag name="lcms">Enable ICC profile support via <pkg>media-libs/lcms</pkg></flag>
		<flag name="libaom">
			Enable AV1 de/encoding via <pkg>media-libs/libaom</pkg> (warning: this
			is the reference implementation and is slower than the alternatives)
		</flag>
		<flag name="libaribb24">Enable ARIB text and caption decoding via <pkg>media-libs/aribb24</pkg></flag>
		<flag name="libilbc">Enable internet Low Bitrate Codec de/encoding support via <pkg>media-libs/libilbc</pkg></flag>
		<flag name="liblc3">Enable Low Complexity Communication Codec de/encoding support via <pkg>media-sound/liblc3</pkg></flag>
		<flag name="libplacebo">Enable use of GPU-accelerated filters from <pkg>media-libs/libplacebo</pkg></flag>
		<flag name="librtmp">
			Enable Real Time Messaging Protocol support via <pkg>media-video/rtmpdump</pkg>
			in addition to FFmpeg's own implementation
		</flag>
		<flag name="libsoxr">Enable use of the audio resampler from <pkg>media-libs/soxr</pkg></flag>
		<flag name="lv2">Enable use of filters through <pkg>media-libs/lv2</pkg></flag>
		<flag name="ocr">Enable Optical Character Recognition (OCR) filter support via <pkg>app-text/tesseract</pkg></flag>
		<flag name="openh264">Enable H.264 encoding support via <pkg>media-libs/openh264</pkg></flag>
		<flag name="openmpt">Enable MPTM tracked music files decoding support via <pkg>media-libs/libopenmpt</pkg></flag>
		<flag name="openssl">
			Enable using <pkg>dev-libs/openssl</pkg> for TLS/HTTPS support
			and other minor functions (USE=gnutls has no effect if set)
		</flag>
		<flag name="postproc">
			Enable libpostproc video post processing library support
			(should not disable this unless need to disable USE=gpl)
		</flag>
		<flag name="qrcode">Enable QR encode generation support via <pkg>media-gfx/qrencode</pkg></flag>
		<flag name="qsv">Enable Intel Quick Sync Video support via <pkg>media-libs/libvpl</pkg></flag>
		<flag name="quirc">Enable QR decoding support via <pkg>media-libs/quirc</pkg></flag>
		<flag name="rabbitmq">Enable AMQP stream support via <pkg>net-libs/rabbitmq-c</pkg></flag>
		<flag name="rav1e">Enable AV1 encoding support via <pkg>media-video/rav1e</pkg></flag>
		<flag name="rubberband">Enable time-stretching and pitch-shifting audio filter support via <pkg>media-libs/rubberband</pkg></flag>
		<flag name="sdl">Enable use of the Simple Direct Layer library (required for the ffplay command)</flag>
		<flag name="shaderc">Enable support for various GPU-accelerated filters using Vulkan compiled with <pkg>media-libs/shaderc</pkg></flag>
		<flag name="snappy">
			Enable Snappy compression support via <pkg>app-arch/snappy</pkg>
			(required for Vidvox Hap encoder support)
		</flag>
		<flag name="sndio">Enable audio output support via <pkg>media-sound/sndio</pkg></flag>
		<flag name="soc">Apply additional patches for efficient playback on some SoCs (e.g. ARM, RISC-V)</flag>
		<flag name="srt">Enable Secure Reliable Transport (SRT) support via <pkg>net-libs/srt</pkg></flag>
		<flag name="ssh">Enable SSH/SFTP support via <pkg>net-libs/libssh</pkg></flag>
		<flag name="svt-av1">Enable AV1 encoding support via <pkg>media-libs/svt-av1</pkg></flag>
		<flag name="truetype">
			Enable drawtext filter support via <pkg>media-libs/freetype</pkg>
			and <pkg>media-libs/harfbuzz</pkg>
		</flag>
		<flag name="twolame">
			Enable MP2 encoding support via <pkg>media-sound/twolame</pkg>
			in addition to FFmpeg's own implementation
		</flag>
		<flag name="vidstab">Enable video stabilization filter support via <pkg>media-libs/vidstab</pkg></flag>
		<flag name="vpx">
			Enable VP8 and VP9 de/encoding support via <pkg>media-libs/libvpx</pkg>
			in addition to FFmpeg's own implementation (for decoding only)
		</flag>
		<flag name="x265">Enable H.265/HEVC encoding support via <pkg>media-libs/x265</pkg></flag>
		<flag name="xml">Enable Dynamic Adaptive Streaming over HTTP (DASH) stream support using <pkg>dev-libs/libxml2</pkg></flag>
		<flag name="zeromq">Enable ZMQ command receiver filter and streaming support via <pkg>net-libs/zeromq</pkg></flag>
		<flag name="zimg">Enable zscale filter support using <pkg>media-libs/zimg</pkg></flag>
		<flag name="zvbi">Enable teletext decoding support via <pkg>media-libs/zvbi</pkg></flag>
	</use>
	<upstream>
		<bugs-to>https://trac.ffmpeg.org/</bugs-to>
		<doc>https://ffmpeg.org/documentation.html</doc>
		<remote-id type="cpe">cpe:/a:ffmpeg:ffmpeg</remote-id>
		<remote-id type="github">FFmpeg/FFmpeg</remote-id>
	</upstream>
</pkgmetadata>

=== calculatelinux/gentoo/app-admin/sysstat/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person" proxied="yes">
		<email>brahmajit.xyz@gmail.com</email>
		<name>Brahmajit Das</name>
	</maintainer>
	<maintainer type="project" proxied="proxy">
		<email>proxy-maint@gentoo.org</email>
		<name>Proxy Maintainers</name>
	</maintainer>
	<use>
		<flag name="dcron">Adjust cronjobs to work properly under <pkg>sys-process/dcron</pkg></flag>
	</use>
	<upstream>
		<bugs-to>https://github.com/sysstat/sysstat/issues</bugs-to>
		<changelog>https://github.com/sysstat/sysstat/blob/master/CHANGES</changelog>
		<doc>https://github.com/sysstat/sysstat/wiki</doc>
		<remote-id type="github">sysstat/sysstat</remote-id>
		<remote-id type="cpe">cpe:/a:sysstat_project:sysstat</remote-id>
	</upstream>
</pkgmetadata>

=== calculatelinux/gentoo/sys-power/acpilight/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person" proxied="yes">
		<email>brahmajit.xyz@gmail.com</email>
		<name>Brahmajit Das</name>
	</maintainer>
	<maintainer type="project" proxied="proxy">
		<email>proxy-maint@gentoo.org</email>
		<name>Proxy Maintainers</name>
	</maintainer>
	<upstream>
		<remote-id type="gitlab">wavexx/acpilight</remote-id>
	</upstream>
</pkgmetadata>

=== calculatelinux/gentoo/sys-cluster/sanlock/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>mschiff@gentoo.org</email>
		<name>Marc Schiffbauer</name>
	</maintainer>
	<maintainer type="project">
		<email>cluster@gentoo.org</email>
		<name>Gentoo Cluster Project</name>
	</maintainer>
	<upstream>
		<remote-id type="codeberg">sanlock/sanlock</remote-id>
	</upstream>
</pkgmetadata>
