=== calculatelinux/gentoo/metadata/dtd/metadata.dtd
<!-- Metadata for a category -->
<!ELEMENT catmetadata ( (longdescription)* )>

<!-- Metadata for a package -->
<!ELEMENT pkgmetadata ( (maintainer|longdescription|slots|stabilize-allarches|straight-to-stable|use|upstream)* )>

  <!-- One tag for each maintainer of a package, multiple allowed-->
  <!ELEMENT maintainer (email|name|description)+>
  <!-- type attribute determines whether the maintainer is a person or a project.
    Unknown is added to handle <maintainer/>s in <upstream/>s. Using it (or no
    explicit type) for Gentoo maintainers is prohibited. -->
  <!ATTLIST maintainer type (person|project|unknown) "unknown">
  <!-- proxied attribute determines whether the maintainer is a proxied
    maintainer (yes), regular dev (no) or a proxy for somebody (proxy). It is
    valid only for Gentoo maintainers. -->
  <!ATTLIST maintainer proxied (yes|no|proxy) "no">

  <!-- A long description of the package in freetext-->
  <!ELEMENT longdescription (#PCDATA|pkg|cat)* >

  <!-- A description of the packages SLOTs -->
  <!ELEMENT slots ((slot)*,subslots?) >
    <!-- A particular SLOT -->
    <!ELEMENT slot (#PCDATA)* >
      <!-- name attribute holds the name of the SLOT, for sub-SLOTS
      use the subslots element. A slot name of '*' can be used to
      indicate a single description applying to all the slots in which
      case no other <slot/> elements may be present. -->
      <!ATTLIST slot name CDATA #REQUIRED >
    <!-- The meaning of sub-SLOTs for the whole package -->
    <!ELEMENT subslots (#PCDATA)* >

  <!-- whether it's possible to stabilize ALLARCHES -->
  <!ELEMENT stabilize-allarches EMPTY>

  <!-- whether stable keywords should be retained on version bumps -->
  <!ELEMENT straight-to-stable EMPTY>

  <!-- description of what this USE flag does for this package -->
  <!ELEMENT use (flag)* >
    <!ELEMENT flag (#PCDATA|pkg|cat)* >
      <!-- name attribute holds the name of the USE flag -->
      <!ATTLIST flag name CDATA #REQUIRED >

  <!-- upstream metadata information (maintainers, upstream docs,..) -->
  <!ELEMENT upstream (maintainer|changelog|doc|bugs-to|remote-id)* >
    <!-- Due to the limitation of DTD this will also allow a status
      attribute for the package maintainer element. Please note that
      the usage of the status attribute is nevertheless _only_ allowed
      in the upstream maintainer element. -->
    <!ATTLIST maintainer status (active|inactive|unknown) "unknown" >
    <!-- URL where the upstream changelog can be found -->
    <!ELEMENT changelog (#PCDATA)>
    <!-- URL where the location of the upstream documentation can be found -->
    <!ELEMENT doc (#PCDATA)>
      <!ATTLIST doc lang CDATA "en" >
    <!-- location where to report bugs
      (may also be an email address prefixed with mailto:) -->
    <!ELEMENT bugs-to (#PCDATA)>
    <!-- specify a type of package identification tracker -->
    <!ELEMENT remote-id (#PCDATA)>
      <!ATTLIST remote-id type (bitbucket|codeberg|cpan|cpan-module|cpe|cran|ctan|freedesktop-gitlab|gentoo|github|gitlab|gnome-gitlab|google-code|hackage|heptapod|kde-invent|launchpad|osdn|pear|pecl|pypi|rubygems|savannah|savannah-nongnu|sourceforge|sourcehut|vim) #REQUIRED>

  <!-- category/package information for cross-linking in descriptions
    and useflag descriptions -->
  <!ELEMENT pkg (#PCDATA) >
  <!ELEMENT cat (#PCDATA) >

<!-- Common attributes -->

<!-- the lang attribute, specifies the language of this tag in the
  form of an IETF (BCP 47) language tag. This is only useful for
  descriptions of various kinds. If a tag with this attribute is
  included there must be a description in the default language "en" -->
  <!ATTLIST description lang CDATA "en" >
  <!ATTLIST longdescription lang CDATA "en" >
  <!ATTLIST slots lang CDATA "en" >
  <!ATTLIST use lang CDATA "en" >

<!-- The restrict attribute, this attribute specifies restrictions on
  the applicability of tags on versions. The format of this attribute is
  equal to the format of DEPEND lines in ebuilds. Only package
  dependency specifications conforming to EAPI=0 syntax are allowed.
  The dependency specification may only contain references to the
  package itself and no other package.

  For required tags, there must be either an unrestricted version, or a
  version that is default restricted. -->
  <!ATTLIST maintainer restrict CDATA #IMPLIED >
  <!ATTLIST longdescription restrict CDATA #IMPLIED >
  <!ATTLIST flag restrict CDATA #IMPLIED >
  <!ATTLIST stabilize-allarches restrict CDATA #IMPLIED >
  <!ATTLIST straight-to-stable restrict CDATA #IMPLIED >

<!-- standard parts -->
<!-- an email address -->
<!ELEMENT email (#PCDATA) >
<!-- the name of a person (maintainer, contributor) -->
<!ELEMENT name (#PCDATA) >
<!-- A description of a maintainer or change -->
<!ELEMENT description (#PCDATA) >

=== calculatelinux/gentoo/dev-python/requests-ratelimiter/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="project">
		<email>python@gentoo.org</email>
	</maintainer>
	<stabilize-allarches/>
	<upstream>
		<doc>https://requests-ratelimiter.readthedocs.io/</doc>
		<remote-id type="github">JWCook/requests-ratelimiter</remote-id>
		<remote-id type="pypi">requests-ratelimiter</remote-id>
	</upstream>
</pkgmetadata>

=== calculatelinux/gentoo/media-sound/beets/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer type="person" proxied="yes">
    <email>vimproved@inventati.org</email>
    <name>Violet Purcell</name>
  </maintainer>
  <maintainer type="person" proxied="yes">
    <email>guillaumeseren@gmail.com</email>
    <name>Guillaume Seren</name>
  </maintainer>
  <maintainer type="project" proxied="proxy">
    <email>proxy-maint@gentoo.org</email>
    <name>Proxy Maintainers</name>
  </maintainer>
  <longdescription lang="en">
        The purpose of beets is to get your music collection right once and for
        all. It catalogs your collection, automatically improving its metadata as
        it goes using the MusicBrainz database. (It also downloads cover art for
        albums it imports.) Then it provides a bouquet of tools for manipulating
        and accessing your music.

        Because beets is designed as a library, it can do almost anything you can
        imagine for your music collection. Via plugins, beets becomes a panacea:
        * Embed and extract album art from files' tags.
        * Listen to your library with a music player that speaks the MPD protocol
        and works with a staggering variety of interfaces.
        * Fetch lyrics for all your songs from databases on the Web.
        * Manage your MusicBrainz music collection.
        * Analyze music files' metadata from the command line.
        * Clean up crufty tags left behind by other, less-awesome tools.
        * Browse your music library graphically through a Web browser and play it
        in any browser that supports HTML5 Audio.

        If beets doesn't do what you want yet, writing your own plugin is
        shockingly simple if you know a little Python.
  </longdescription>
  <stabilize-allarches/>
  <upstream>
    <doc>https://beets.readthedocs.io/</doc>
    <remote-id type="pypi">beets</remote-id>
    <remote-id type="github">beetbox/beets</remote-id>
  </upstream>
</pkgmetadata>

=== calculatelinux/gentoo/sci-astronomy/ser-player/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person" proxied="yes">
		<email>mario.haustein@hrz.tu-chemnitz.de</email>
		<name>Mario Haustein</name>
	</maintainer>
	<maintainer type="project" proxied="proxy">
		<email>proxy-maint@gentoo.org</email>
		<name>Proxy Maintainers</name>
	</maintainer>
	<upstream>
		<remote-id type="github">lock042/ser-player</remote-id>
	</upstream>
</pkgmetadata>

=== calculatelinux/gentoo/media-libs/mesa/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer type="project">
    <email>x11@gentoo.org</email>
    <name>X11</name>
  </maintainer>
  <use>
    <flag name="llvm">Enable LLVM backend for Gallium3D.</flag>
    <flag name="lm-sensors">Enable Gallium HUD lm-sensors support.</flag>
    <flag name="opencl">Enable the Rusticl Gallium OpenCL state tracker.</flag>
    <flag name="proprietary-codecs">Enable codecs for patent-encumbered audio and video formats.</flag>
    <flag name="sysprof">Enable profiling data capture support using <pkg>dev-util/sysprof-capture</pkg></flag>
    <flag name="wayland">Enable support for <pkg>dev-libs/wayland</pkg></flag>
  </use>
  <upstream>
    <remote-id type="cpe">cpe:/a:mesa3d:mesa</remote-id>
    <remote-id type="freedesktop-gitlab">mesa/mesa</remote-id>
  </upstream>
</pkgmetadata>

=== calculatelinux/gentoo/sys-apps/bat/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person" proxied="yes">
		<email>vi@vimproved.dev</email>
		<name>Violet Purcell</name>
	</maintainer>
	<maintainer type="project" proxied="proxy">
		<email>proxy-maint@gentoo.org</email>
		<name>Proxy Maintainers</name>
	</maintainer>
	<longdescription lang="en">
		A cat(1) clone with wings

		bat tries to achieve the following goals:

			- Provide beautiful, advanced syntax highlighting
			- Integrate with Git to show file modifications
			- Be a drop-in replacement for (POSIX) cat
			- Offer a user-friendly command-line interface
	</longdescription>
	<upstream>
		<bugs-to>https://github.com/sharkdp/bat/issues</bugs-to>
		<remote-id type="github">sharkdp/bat</remote-id>
	</upstream>
</pkgmetadata>

=== calculatelinux/gentoo/media-sound/musescore/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person" proxied="yes">
		<email>vi@vimproved.dev</email>
		<name>Violet Purcell</name>
	</maintainer>
	<maintainer type="project" proxied="proxy">
		<email>proxy-maint@gentoo.org</email>
		<name>Proxy Maintainers</name>
	</maintainer>
	<maintainer type="project">
		<email>sound@gentoo.org</email>
		<name>Gentoo Sound project</name>
	</maintainer>
	<upstream>
		<remote-id type="sourceforge">mscore</remote-id>
		<remote-id type="github">musescore/MuseScore</remote-id>
	</upstream>
	<use>
		<flag name="pipewire">Enable PipeWire audio support (upstream's default)</flag>
		<flag name="video">Support exporting scores as videos using the command line</flag>
		<flag name="websockets">Enable websockets support</flag>
	</use>
</pkgmetadata>

=== calculatelinux/gentoo/sci-mathematics/octave/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer type="project">
    <email>sci-mathematics@gentoo.org</email>
    <name>Gentoo Mathematics Project</name>
  </maintainer>
  <longdescription lang="en">
  Octave is a high-level language, primarily intended for numerical computations. It provides a convenient command line interface for solving linear and nonlinear problems numerically, and for performing other numerical experiments. It may also be used as a batch-oriented language.
  </longdescription>
  <use>
    <flag name="glpk">Add support for <pkg>sci-mathematics/glpk</pkg> for linear programming</flag>
    <flag name="gnuplot">Use <pkg>sci-visualization/gnuplot</pkg> to render plots if OpenGL is unavailable</flag>
    <flag name="imagemagick">Use <pkg>media-gfx/graphicsmagick</pkg> to read and write images</flag>
    <flag name="json">Allow using jsonencode and jsondecode commands via <pkg>dev-libs/rapidjson</pkg></flag>
    <flag name="klu">Add support for KLU (<pkg>sci-libs/klu</pkg>)</flag>
    <flag name="qhull">Add support for <pkg>media-libs/qhull</pkg>, to allow `delaunay', `convhull', and related functions</flag>
    <flag name="qrupdate">Add support for <pkg>sci-libs/qrupdate</pkg>for QR and Cholesky update functions</flag>
    <flag name="sparse">Add enhanced support for sparse matrix algebra with SuiteSparse</flag>
    <flag name="spqr">Add support for SPQR (<pkg>sci-libs/spqr</pkg>)</flag>
    <flag name="sundials">Enable the ode15i and ode15s ODE solvers using <pkg>sci-libs/sundials</pkg></flag>
  </use>
  <upstream>
    <bugs-to>https://savannah.gnu.org/bugs/?group=octave</bugs-to>
    <changelog>https://octave.org/news.html</changelog>
    <doc>https://docs.octave.org/latest/</doc>
    <remote-id type="savannah">octave</remote-id>
  </upstream>
</pkgmetadata>

=== calculatelinux/gentoo/media-plugins/audacious-plugins/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="project">
		<email>sound@gentoo.org</email>
		<name>Gentoo Sound project</name>
	</maintainer>
	<use>
		<flag name="ampache">Support controlling audacious via ampache</flag>
		<flag name="bs2b">Enable Bauer Bauer stereophonic-to-binaural headphone filter</flag>
		<flag name="cue">Support CUE sheets using the libcue library</flag>
		<flag name="fluidsynth">Support FluidSynth as MIDI synth backend</flag>
		<flag name="gme">Support various gaming console music formats</flag>
		<flag name="http">Support HTTP streams through neon</flag>
		<flag name="openmpt">Add support for OpenMPT</flag>
		<flag name="pipewire">Build the PipeWire output plugin</flag>
		<flag name="qtmedia">Enable playback via <pkg>dev-qt/qtmultimedia</pkg></flag>
		<flag name="scrobbler">Build with scrobbler/LastFM submission support</flag>
		<flag name="soxr">Build with SoX Resampler support</flag>
		<flag name="streamtuner">Build the streamtuner plugin</flag>
	</use>
	<upstream>
		<remote-id type="github">audacious-media-player/audacious-plugins</remote-id>
	</upstream>
</pkgmetadata>
